DROP DATABASE IF EXISTS TODOAPP;
CREATE DATABASE TODOAPP;
USE TODOAPP

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(1000) NOT NULL
);

DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    userId INT NOT NULL,
    status INT NOT NULL,
    date DATETIME,
    CONSTRAINT FK_USER_TASK FOREIGN KEY (userId) REFERENCES USER (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP USER IF EXISTS 'todoapp';
CREATE USER 'todoapp'@'%' IDENTIFIED BY 'todoapp';
GRANT SELECT, INSERT, UPDATE, DELETE ON TODOAPP.* TO 'todoapp'@'%';