DROP DATABASE IF EXISTS TODOAPP;
CREATE DATABASE TODOAPP;
USE TODOAPP

CREATE TABLE USER (
    login VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(1000) NOT NULL
);

CREATE TABLE TASK (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    task VARCHAR(4000) NOT NULL,
    login VARCHAR(100) NOT NULL,
    status BOOLEAN NOT NULL,
    CONSTRAINT FK_USER_TASK FOREIGN KEY (login) REFERENCES USER (login) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP USER IF EXISTS 'todoapp';
CREATE USER 'todoapp'@'%' IDENTIFIED BY 'todoapp';
GRANT SELECT, INSERT, UPDATE, DELETE ON TODOAPP.* TO 'todoapp'@'%';