CREATE DATABASE IF NOT EXISTS TODOAPP;
USE TODOAPP

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    PRIMARY KEY (login)
);

DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (
    id INT NOT NULL AUTO_INCREMENT,
    task VARCHAR(500) NOT NULL,
    login VARCHAR(200) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_USER_TASK FOREIGN KEY (login) REFERENCES USER (login) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP USER IF EXISTS 'todoapp';
CREATE USER 'todoapp'@'%' IDENTIFIED BY 'todoapp';
GRANT SELECT, INSERT, UPDATE, DELETE ON TODOAPP.* TO 'todoapp'@'%';